print("Hello World")
counties = ["Araphoe", "Denver", "Jefferson"]
print(counties)
print(counties[0])
print(counties[0:2])
print(counties[:2])
counties.append("El Paso")
print(counties)
counties.insert(2, "El Paso")
print(counties)
counties.remove("El Paso")
print(counties)
counties.pop(3)
print(counties)
counties[0] = "El Paso"
counties.pop(1)
print(counties)
counties.insert(2, "Denver")
counties.append("Arapahoe")
print(counties)
